# fly.toml app configuration file generated for rjprice04-protohackers on 2023-12-21T21:14:28-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rjprice04-protohackers"
primary_region = "ord"

[build]

[[services]]
  internal_port = 10000
  protocol = "tcp"
  
  [[services.ports]]
    port = 10000

[[services]]
  internal_port = 10000
  protocol = "udp"
  
  [[services.ports]]
    port = 10000
